### ISSUE TITLE
Unable to read GRIB2 files distributed by Meteo France

### ISSUE THREAD

**Issue by maximlt** [ecmwf/cfgrib#102]
Hi and thanks for that nice package ;)

I've just tried to open a GRIB2 file distributed by Meteo France (see the download page [here](https://donneespubliques.meteofrance.fr/?fond=produit&id_produit=131&id_rubrique=51)) as a result of the AROME model. I get the following error after running `import cfgrib; cfgrib.open_dataset("AROME_0.01_SP1_28H_201909221200.grib2")`:
```
---------------------------------------------------------------------------
GribInternalError                         Traceback (most recent call last)
<ipython-input-6-281edebd33a5> in <module>
----> 1 cfgrib.open_datasets("dataMF\AROME_0.01_SP1_28H_201909221200.grib2")

~\Miniconda3\envs\readgrib2\lib\site-packages\cfgrib\xarray_store.py in open_datasets(path, no_warn, backend_kwargs, **kwargs)
    101     backend_kwargs = backend_kwargs.copy()
    102     backend_kwargs['squeeze'] = False
--> 103     datasets = open_variable_datasets(path, backend_kwargs=backend_kwargs, **kwargs)
    104 
    105     type_of_level_datasets = {}

~\Miniconda3\envs\readgrib2\lib\site-packages\cfgrib\xarray_store.py in open_variable_datasets(path, backend_kwargs, **kwargs)
     87         bk['filter_by_keys'] = backend_kwargs.get('filter_by_keys', {}).copy()
     88         bk['filter_by_keys']['paramId'] = param_id
---> 89         datasets.extend(raw_open_datasets(path, bk, **kwargs))
     90     return datasets
     91 

~\Miniconda3\envs\readgrib2\lib\site-packages\cfgrib\xarray_store.py in raw_open_datasets(path, backend_kwargs, **kwargs)
     63     datasets = []
     64     try:
---> 65         datasets.append(open_dataset(path, backend_kwargs=backend_kwargs, **kwargs))
     66     except DatasetBuildError as ex:
     67         fbks.extend(ex.args[2])

~\Miniconda3\envs\readgrib2\lib\site-packages\cfgrib\xarray_store.py in open_dataset(path, **kwargs)
     37         raise ValueError("only engine=='cfgrib' is supported")
     38     kwargs['engine'] = 'cfgrib'
---> 39     return xr.backends.api.open_dataset(path, **kwargs)
     40 
     41 

~\Miniconda3\envs\readgrib2\lib\site-packages\xarray\backends\api.py in open_dataset(filename_or_obj, group, decode_cf, mask_and_scale, decode_times, autoclose, concat_characters, decode_coords, engine, chunks, lock, cache, drop_variables, backend_kwargs, use_cftime)
    515         elif engine == "cfgrib":
    516             store = backends.CfGribDataStore(
--> 517                 filename_or_obj, lock=lock, **backend_kwargs
    518             )
    519 

~\Miniconda3\envs\readgrib2\lib\site-packages\xarray\backends\cfgrib_.py in __init__(self, filename, lock, **backend_kwargs)
     41             lock = ECCODES_LOCK
     42         self.lock = ensure_lock(lock)
---> 43         self.ds = cfgrib.open_file(filename, **backend_kwargs)
     44 
     45     def open_store_variable(self, name, var):

~\Miniconda3\envs\readgrib2\lib\site-packages\cfgrib\dataset.py in open_file(path, grib_errors, indexpath, filter_by_keys, **kwargs)
    602     """Open a GRIB file as a ``cfgrib.Dataset``."""
    603     index = open_fileindex(path, grib_errors, indexpath, filter_by_keys)
--> 604     return Dataset(*build_dataset_components(index, **kwargs))

~\Miniconda3\envs\readgrib2\lib\site-packages\cfgrib\dataset.py in build_dataset_components(index, errors, encode_cf, timestamp, squeeze, log)
    528         try:
    529             dims, data_var, coord_vars = build_variable_components(
--> 530                 var_index, encode_cf, filter_by_keys, errors=errors, squeeze=squeeze
    531             )
    532         except DatasetBuildError as ex:

~\Miniconda3\envs\readgrib2\lib\site-packages\cfgrib\dataset.py in build_variable_components(index, encode_cf, filter_by_keys, log, errors, squeeze)
    463     header_shape = tuple(coord_vars[d].data.size for d in header_dimensions)
    464 
--> 465     geo_dims, geo_shape, geo_coord_vars = build_geography_coordinates(index, encode_cf, errors)
    466     dimensions = header_dimensions + geo_dims
    467     shape = header_shape + geo_shape

~\Miniconda3\envs\readgrib2\lib\site-packages\cfgrib\dataset.py in build_geography_coordinates(index, encode_cf, errors, log)
    355         geo_dims = ('latitude', 'longitude')  # type: T.Tuple[str, ...]
    356         geo_shape = (index.getone('Ny'), index.getone('Nx'))  # type: T.Tuple[int, ...]
--> 357         latitudes = np.array(first['distinctLatitudes'])
    358         geo_coord_vars['latitude'] = Variable(
    359             dimensions=('latitude',), data=latitudes, attributes=COORD_ATTRS['latitude'].copy()

~\Miniconda3\envs\readgrib2\lib\site-packages\cfgrib\messages.py in __getitem__(self, item)
    176             return getter(self)
    177         else:
--> 178             return super(ComputedKeysMessage, self).__getitem__(item)
    179 
    180     def __iter__(self):

~\Miniconda3\envs\readgrib2\lib\site-packages\cfgrib\messages.py in __getitem__(self, item)
    128     def __getitem__(self, item):
    129         # type: (str) -> T.Any
--> 130         return self.message_get(item)
    131 
    132     def __setitem__(self, item, value):

~\Miniconda3\envs\readgrib2\lib\site-packages\cfgrib\messages.py in message_get(self, item, key_type, default)
     90         """Get value of a given key as its native or specified type."""
     91         try:
---> 92             values = eccodes.codes_get_array(self.codes_id, item, key_type)
     93             if values is None:
     94                 values = ['unsupported_key_type']

~\Miniconda3\envs\readgrib2\lib\site-packages\cfgrib\bindings.py in codes_get_array(handle, key, key_type, size, length, log)
    363         key_type = codes_get_native_type(handle, key)
    364     if size is None:
--> 365         size = codes_get_size(handle, key)
    366 
    367     if key_type == int:

~\Miniconda3\envs\readgrib2\lib\site-packages\cfgrib\bindings.py in codes_get_size(handle, key)
    214     """
    215     size = ffi.new('size_t *')
--> 216     _codes_get_size(handle, key.encode(ENC), size)
    217     return size[0]
    218 

~\Miniconda3\envs\readgrib2\lib\site-packages\cfgrib\bindings.py in wrapper(*args)
    163                 raise ERROR_MAP[code](code)
    164             else:
--> 165                 raise GribInternalError(code)
    166 
    167     return wrapper

GribInternalError: ('Function not yet implemented (-4).', -4)
```

This is the used conda environment:
```
# Name                    Version                   Build  Channel
attrs                     19.1.0                     py_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
bleach                    3.1.0                      py_0    conda-forge
bzip2                     1.0.8                hfa6e2cd_1    conda-forge
ca-certificates           2019.9.11            hecc5488_0    conda-forge
certifi                   2019.6.16                py37_1
cffi                      1.12.3           py37hb32ad35_0    conda-forge
cfgrib                    0.9.7.1                    py_0    conda-forge
click                     7.0                        py_0    conda-forge
colorama                  0.4.1                      py_0    conda-forge
curl                      7.65.3               h4496350_0    conda-forge
decorator                 4.4.0                      py_0    conda-forge
defusedxml                0.5.0                      py_1    conda-forge
eccodes                   2.13.1               h0dc745f_1    conda-forge
entrypoints               0.3                   py37_1000    conda-forge
hdf4                      4.2.13            hf8e6fe8_1002    conda-forge
hdf5                      1.10.5          nompi_ha405e13_1103    conda-forge
icu                       64.2                 he025d50_1    conda-forge
intel-openmp              2019.5                      281
ipykernel                 5.1.2            py37h5ca1d4c_0    conda-forge
ipython                   7.8.0            py37h5ca1d4c_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.5.1                      py_0    conda-forge
jedi                      0.15.1                   py37_0    conda-forge
jinja2                    2.10.1                     py_0    conda-forge
jpeg                      9c                hfa6e2cd_1001    conda-forge
jsonschema                3.0.2                    py37_0    conda-forge
jupyter                   1.0.0                      py_2    conda-forge
jupyter_client            5.3.1                      py_0    conda-forge
jupyter_console           6.0.0                      py_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
krb5                      1.16.3            hdd46e55_1001    conda-forge
libblas                   3.8.0                    12_mkl    conda-forge
libcblas                  3.8.0                    12_mkl    conda-forge
libcurl                   7.65.3               h4496350_0    conda-forge
liblapack                 3.8.0                    12_mkl    conda-forge
libnetcdf                 4.6.2             h376842a_1003    conda-forge
libpng                    1.6.37               h7602738_0    conda-forge
libsodium                 1.0.17               h2fa13f4_0    conda-forge
libssh2                   1.8.2                h642c060_2    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
markupsafe                1.1.1            py37hfa6e2cd_0    conda-forge
mistune                   0.8.4           py37hfa6e2cd_1000    conda-forge
mkl                       2019.4                      245
msys2-conda-epoch         20160418                      1
nbconvert                 5.6.0                    py37_1    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
notebook                  6.0.1                    py37_0    conda-forge
numpy                     1.15.4          py37h8078771_1002    conda-forge
openssl                   1.1.1c               hfa6e2cd_0    conda-forge
pandas                    0.25.1           py37he350917_0    conda-forge
pandoc                    2.7.3                         0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.5.1                      py_0    conda-forge
pickleshare               0.7.5                 py37_1000    conda-forge
pip                       19.2.3                   py37_0    conda-forge
prometheus_client         0.7.1                      py_0    conda-forge
prompt_toolkit            2.0.9                      py_0    conda-forge
pycparser                 2.19                     py37_1    conda-forge
pygments                  2.4.2                      py_0    conda-forge
pyqt                      5.9.2            py37h6538335_4    conda-forge
pyrsistent                0.15.4           py37hfa6e2cd_0    conda-forge
python                    3.7.3                h510b542_1    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
pytz                      2019.2                     py_0    conda-forge
pywinpty                  0.5.5                 py37_1000    conda-forge
pyzmq                     18.1.0           py37h16f9016_0    conda-forge
qt                        5.9.7                h506e8af_3    conda-forge
qtconsole                 4.5.5                      py_0    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                41.2.0                   py37_0    conda-forge
sip                       4.19.8          py37h6538335_1000    conda-forge
six                       1.12.0                py37_1000    conda-forge
sqlite                    3.29.0               hfa6e2cd_1    conda-forge
terminado                 0.8.2                    py37_0    conda-forge
testpath                  0.4.2                   py_1001    conda-forge
tk                        8.6.9             hfa6e2cd_1003    conda-forge
tornado                   6.0.3            py37hfa6e2cd_0    conda-forge
traitlets                 4.3.2                 py37_1000    conda-forge
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_0
wcwidth                   0.1.7                      py_1    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.33.6                   py37_0    conda-forge
widgetsnbextension        3.5.1                    py37_0    conda-forge
wincertstore              0.2                   py37_1002    conda-forge
winpty                    0.4.3                         4    conda-forge
xarray                    0.13.0                     py_0    conda-forge
zeromq                    4.3.2                h6538335_2    conda-forge
zlib                      1.2.11            h2fa13f4_1006    conda-forge
```

Any idea about what's going on with that file?

Thanks!

**Comment by alexamici** [comment]
@maximlt I can open a file from the site with no problem on MacOS and *cfgrib* 0.9.7.1 from *conda-forge*.

This looks like a Windows specific bug (I guessed the OS from the paths in your stack trace).

```
$ python
Python 3.7.4 (default, Aug 13 2019, 15:17:50) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import cfgrib
/Users/amici/.conda/envs/ECM/lib/python3.7/site-packages/xarray/core/merge.py:17: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
>>> cfgrib.open_dataset('cfgrib/A
ArithmeticError(  AssertionError(   AttributeError(   
>>> cfgrib.open_dataset('cfgrib/AROME_0.01_HP1_00H_201909240300.grib2')
skipping variable: paramId==131 shortName='u'
Traceback (most recent call last):
  File "/Users/amici/.conda/envs/ECM/lib/python3.7/site-packages/cfgrib/dataset.py", line 547, in build_dataset_components
    dict_merge(variables, coord_vars)
  File "/Users/amici/.conda/envs/ECM/lib/python3.7/site-packages/cfgrib/dataset.py", line 508, in dict_merge
    "key=%r value=%r new_value=%r" % (key, master[key], value)
cfgrib.dataset.DatasetBuildError: key present and new value is different: key='heightAboveGround' value=Variable(dimensions=('heightAboveGround',), data=array([ 20,  50, 100])) new_value=Variable(dimensions=('heightAboveGround',), data=array([20, 50]))
skipping variable: paramId==228246 shortName='u100'
Traceback (most recent call last):
  File "/Users/amici/.conda/envs/ECM/lib/python3.7/site-packages/cfgrib/dataset.py", line 547, in build_dataset_components
    dict_merge(variables, coord_vars)
  File "/Users/amici/.conda/envs/ECM/lib/python3.7/site-packages/cfgrib/dataset.py", line 508, in dict_merge
    "key=%r value=%r new_value=%r" % (key, master[key], value)
cfgrib.dataset.DatasetBuildError: key present and new value is different: key='heightAboveGround' value=Variable(dimensions=('heightAboveGround',), data=array([ 20,  50, 100])) new_value=Variable(dimensions=(), data=100)
skipping variable: paramId==132 shortName='v'
Traceback (most recent call last):
  File "/Users/amici/.conda/envs/ECM/lib/python3.7/site-packages/cfgrib/dataset.py", line 547, in build_dataset_components
    dict_merge(variables, coord_vars)
  File "/Users/amici/.conda/envs/ECM/lib/python3.7/site-packages/cfgrib/dataset.py", line 508, in dict_merge
    "key=%r value=%r new_value=%r" % (key, master[key], value)
cfgrib.dataset.DatasetBuildError: key present and new value is different: key='heightAboveGround' value=Variable(dimensions=('heightAboveGround',), data=array([ 20,  50, 100])) new_value=Variable(dimensions=('heightAboveGround',), data=array([20, 50]))
skipping variable: paramId==228247 shortName='v100'
Traceback (most recent call last):
  File "/Users/amici/.conda/envs/ECM/lib/python3.7/site-packages/cfgrib/dataset.py", line 547, in build_dataset_components
    dict_merge(variables, coord_vars)
  File "/Users/amici/.conda/envs/ECM/lib/python3.7/site-packages/cfgrib/dataset.py", line 508, in dict_merge
    "key=%r value=%r new_value=%r" % (key, master[key], value)
cfgrib.dataset.DatasetBuildError: key present and new value is different: key='heightAboveGround' value=Variable(dimensions=('heightAboveGround',), data=array([ 20,  50, 100])) new_value=Variable(dimensions=(), data=100)
<xarray.Dataset>
Dimensions:            (heightAboveGround: 3, latitude: 1791, longitude: 2801)
Coordinates:
    time               datetime64[ns] ...
    step               timedelta64[ns] ...
  * heightAboveGround  (heightAboveGround) int64 20 50 100
  * latitude           (latitude) float64 55.4 55.39 55.38 ... 37.52 37.51 37.5
  * longitude          (longitude) float64 -12.0 -11.99 -11.98 ... 15.99 16.0
    valid_time         datetime64[ns] ...
Data variables:
    r                  (heightAboveGround, latitude, longitude) float32 ...
Attributes:
    GRIB_edition:            2
    GRIB_centre:             lfpw
    GRIB_centreDescription:  French Weather Service - Toulouse
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             French Weather Service - Toulouse
    history:                 2019-09-24T09:07:35 GRIB to CDM+CF via cfgrib-0....
>>>
```

**Comment by maximlt** [comment]
Thanks for your quick reply!

I'm indeed on Windows. I've just reinstalled `cfgrib` (its very last version) in a new environment and tried to open the exact same file. Got the same error unfortunately :/

There's a little bit more info at the top of the traceback (the first one was copied from a notebook output cell, that one from the interactive python shell), mentionning some ECCODES errors. This seems to be similar to that issue:
https://github.com/conda-forge/eccodes-feedstock/issues/80

```
Python 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 22:01:29) [MSC v
.1900 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import cfgrib
>>> cfgrib.__version__
'0.9.7.2'
>>> cfgrib.open_dataset("AROME_0.01_HP1_00H_201909240300.grib2")
ECCODES ERROR   :  JPEG support not enabled.
ECCODES ERROR   :  unable to get values as double array (Function not yet implem
ented)
ECCODES ERROR   :  unable to create iterator
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Miniconda3\envs\gribtest\lib\site-packages\cfgrib\xarray_
store.py", line 39, in open_dataset
    return xr.backends.api.open_dataset(path, **kwargs)
  File "C:\ProgramData\Miniconda3\envs\gribtest\lib\site-packages\xarray\backend
s\api.py", line 517, in open_dataset
    filename_or_obj, lock=lock, **backend_kwargs
  File "C:\ProgramData\Miniconda3\envs\gribtest\lib\site-packages\xarray\backend
s\cfgrib_.py", line 43, in __init__
    self.ds = cfgrib.open_file(filename, **backend_kwargs)
  File "C:\ProgramData\Miniconda3\envs\gribtest\lib\site-packages\cfgrib\dataset
.py", line 616, in open_file
    return Dataset(*build_dataset_components(index, read_keys=read_keys, **kwarg
s))
  File "C:\ProgramData\Miniconda3\envs\gribtest\lib\site-packages\cfgrib\dataset
.py", line 537, in build_dataset_components
    read_keys=read_keys,
  File "C:\ProgramData\Miniconda3\envs\gribtest\lib\site-packages\cfgrib\dataset
.py", line 466, in build_variable_components
    geo_dims, geo_shape, geo_coord_vars = build_geography_coordinates(index, enc
ode_cf, errors)
  File "C:\ProgramData\Miniconda3\envs\gribtest\lib\site-packages\cfgrib\dataset
.py", line 357, in build_geography_coordinates
    latitudes = np.array(first['distinctLatitudes'])
  File "C:\ProgramData\Miniconda3\envs\gribtest\lib\site-packages\cfgrib\message
s.py", line 178, in __getitem__
    return super(ComputedKeysMessage, self).__getitem__(item)
  File "C:\ProgramData\Miniconda3\envs\gribtest\lib\site-packages\cfgrib\message
s.py", line 130, in __getitem__
    return self.message_get(item)
  File "C:\ProgramData\Miniconda3\envs\gribtest\lib\site-packages\cfgrib\message
s.py", line 92, in message_get
    values = eccodes.codes_get_array(self.codes_id, item, key_type)
  File "C:\ProgramData\Miniconda3\envs\gribtest\lib\site-packages\cfgrib\binding
s.py", line 365, in codes_get_array
    size = codes_get_size(handle, key)
  File "C:\ProgramData\Miniconda3\envs\gribtest\lib\site-packages\cfgrib\binding
s.py", line 216, in codes_get_size
    _codes_get_size(handle, key.encode(ENC), size)
  File "C:\ProgramData\Miniconda3\envs\gribtest\lib\site-packages\cfgrib\binding
s.py", line 165, in wrapper
    raise GribInternalError(code)
cfgrib.bindings.GribInternalError: ('Function not yet implemented (-4).', -4)
```

**Comment by alexamici** [comment]
This is strange, JPEG support should be enabled in the conda-forge eccodes package, see here: 

https://github.com/conda-forge/eccodes-feedstock/blob/master/recipe/bld.bat

Maybe you have another installation of ecCodes on your machine that get precedence over the conda one.

In any event this doesn't look like a *cfgrib* issue. Closing.
