### ISSUE TITLE
Unable to read NCEP MRMS grib2 files

### ISSUE THREAD

**Issue by dmfay** [ecmwf/cfgrib#116]
I'm on OSX and have installed xarray and cfgrib through Anaconda/conda-forge:

```
$ python --version
Python 3.8.0
$ conda env export
name: mypy3env
channels:
  - conda-forge
  - defaults
dependencies:
...
  - cfgrib=0.9.7.3=py_0
...
  - eccodes=2.14.1=ha74ff94_3
...
  - xarray=0.14.1=py_0
```

I'm trying to work with NCEP MultiRadar MultiSensor grib2s such as in https://mrms.ncep.noaa.gov/data/2D/MergedReflectivityQCComposite/ , and always getting the following output/traceback reading files in:

```
$ cfgrib to_netcdf MRMS_MergedReflectivityQCComposite_00.50_20191209-210032.grib2
libpng warning: Application built with libpng-1.4.12 but running with 1.6.37
ECCODES ERROR   :  unable to get values as double array (Decoding invalid)
ECCODES ERROR   :  unable to create iterator
Traceback (most recent call last):
  File "/Users/dian/work/anaconda/envs/mypy3env/bin/cfgrib", line 10, in <module>
    sys.exit(cfgrib_cli())
  File "/Users/dian/work/anaconda/envs/mypy3env/lib/python3.8/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/dian/work/anaconda/envs/mypy3env/lib/python3.8/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/dian/work/anaconda/envs/mypy3env/lib/python3.8/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/dian/work/anaconda/envs/mypy3env/lib/python3.8/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/dian/work/anaconda/envs/mypy3env/lib/python3.8/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/dian/work/anaconda/envs/mypy3env/lib/python3.8/site-packages/cfgrib/__main__.py", line 56, in to_netcdf
    ds = xr.open_mfdataset(inpaths, engine=engine)
  File "/Users/dian/work/anaconda/envs/mypy3env/lib/python3.8/site-packages/xarray/backends/api.py", line 900, in open_mfdataset
    datasets = [open_(p, **open_kwargs) for p in paths]
  File "/Users/dian/work/anaconda/envs/mypy3env/lib/python3.8/site-packages/xarray/backends/api.py", line 900, in <listcomp>
    datasets = [open_(p, **open_kwargs) for p in paths]
  File "/Users/dian/work/anaconda/envs/mypy3env/lib/python3.8/site-packages/xarray/backends/api.py", line 516, in open_dataset
    store = backends.CfGribDataStore(
  File "/Users/dian/work/anaconda/envs/mypy3env/lib/python3.8/site-packages/xarray/backends/cfgrib_.py", line 43, in __init__
    self.ds = cfgrib.open_file(filename, **backend_kwargs)
  File "/Users/dian/work/anaconda/envs/mypy3env/lib/python3.8/site-packages/cfgrib/dataset.py", line 628, in open_file
    return Dataset(*build_dataset_components(index, read_keys=read_keys, **kwargs))
  File "/Users/dian/work/anaconda/envs/mypy3env/lib/python3.8/site-packages/cfgrib/dataset.py", line 542, in build_dataset_components
    dims, data_var, coord_vars = build_variable_components(
  File "/Users/dian/work/anaconda/envs/mypy3env/lib/python3.8/site-packages/cfgrib/dataset.py", line 476, in build_variable_components
    geo_dims, geo_shape, geo_coord_vars = build_geography_coordinates(index, encode_cf, errors)
  File "/Users/dian/work/anaconda/envs/mypy3env/lib/python3.8/site-packages/cfgrib/dataset.py", line 357, in build_geography_coordinates
    latitudes = np.array(first['distinctLatitudes'])
  File "/Users/dian/work/anaconda/envs/mypy3env/lib/python3.8/site-packages/cfgrib/messages.py", line 178, in __getitem__
    return super(ComputedKeysMessage, self).__getitem__(item)
  File "/Users/dian/work/anaconda/envs/mypy3env/lib/python3.8/site-packages/cfgrib/messages.py", line 130, in __getitem__
    return self.message_get(item)
  File "/Users/dian/work/anaconda/envs/mypy3env/lib/python3.8/site-packages/cfgrib/messages.py", line 92, in message_get
    values = eccodes.codes_get_array(self.codes_id, item, key_type)
  File "/Users/dian/work/anaconda/envs/mypy3env/lib/python3.8/site-packages/cfgrib/bindings.py", line 365, in codes_get_array
    size = codes_get_size(handle, key)
  File "/Users/dian/work/anaconda/envs/mypy3env/lib/python3.8/site-packages/cfgrib/bindings.py", line 216, in codes_get_size
    _codes_get_size(handle, key.encode(ENC), size)
  File "/Users/dian/work/anaconda/envs/mypy3env/lib/python3.8/site-packages/cfgrib/bindings.py", line 165, in wrapper
    raise GribInternalError(code)
cfgrib.bindings.GribInternalError: ('Decoding invalid (-13).', -13)
```

**Comment by alexamici** [comment]
```
libpng warning: Application built with libpng-1.4.12 but running with 1.6.37
ECCODES ERROR   :  unable to get values as double array (Decoding invalid)
ECCODES ERROR   :  unable to create iterator
```
Looks like a problem in the *conda* environment that makes *ecCodes* crash.

You should probably report the issue against the *conda-forge* package of *ecCodes* https://github.com/conda-forge/eccodes-feedstock.

**Comment by dmfay** [comment]
Will do, thanks!

**Comment by dmfay** [comment]
Alright, progress on the ecCodes side and now I'm back :) `to_netcdf` is giving me a different traceback after a couple seconds' wait now. Unfortunately it doesn't seem especially helpful:

```
$ cfgrib to_netcdf MRMS_MergedReflectivityQCComposite_00.50_20191209-210032.grib2
/Users/dian/work/anaconda/envs/mypy3env/lib/python3.8/site-packages/cfgrib/__main__.py:56: FutureWarning: In xarray version 0.15 the default behaviour of `open_mfdataset`
will change. To retain the existing behavior, pass
combine='nested'. To use future default behavior, pass
combine='by_coords'. See
http://xarray.pydata.org/en/stable/combining.html#combining-multi

  ds = xr.open_mfdataset(inpaths, engine=engine)
/Users/dian/work/anaconda/envs/mypy3env/lib/python3.8/site-packages/xarray/backends/api.py:926: FutureWarning: The datasets supplied have global dimension coordinates. You may want
to use the new `combine_by_coords` function (or the
`combine='by_coords'` option to `open_mfdataset`) to order the datasets
before concatenation. Alternatively, to continue concatenating based
on the order the datasets are supplied in future, please use the new
`combine_nested` function (or the `combine='nested'` option to
open_mfdataset).
  combined = auto_combine(
Exception ignored in: <function Pool.__del__ at 0x119206ee0>
Traceback (most recent call last):
  File "/Users/dian/work/anaconda/envs/mypy3env/lib/python3.8/multiprocessing/pool.py", line 268, in __del__
  File "/Users/dian/work/anaconda/envs/mypy3env/lib/python3.8/multiprocessing/queues.py", line 362, in put
AttributeError: 'NoneType' object has no attribute 'dumps'
```

**Comment by alexamici** [comment]
@dmfay I had to fight against the *ecCodes* error (that I solved by `conda install eccodes=2.15.0`) but then I can't reproduce the error:
```
$ cfgrib to_netcdf MRMS_MergedReflectivityQCComposite_00.50_20191216-044830.grib2
ECCODES ERROR   :  Truncating time: non-zero seconds(30) ignored
ECCODES ERROR   :  Truncating time: non-zero seconds(30) ignored
ECCODES ERROR   :  Truncating time: non-zero seconds(30) ignored
ECCODES ERROR   :  Truncating time: non-zero seconds(30) ignored
(ECM) sibylla:cfgrib amici$ ncdump -h MRMS_MergedReflectivityQCComposite_00.50_20191216-044830.nc
netcdf MRMS_MergedReflectivityQCComposite_00.50_20191216-044830 {
dimensions:
	latitude = 3500 ;
	longitude = 7000 ;
variables:
	int64 time ;
		time:long_name = "initial time of forecast" ;
		time:standard_name = "forecast_reference_time" ;
		time:units = "seconds since 1970-01-01" ;
		time:calendar = "proleptic_gregorian" ;
	double step ;
		step:_FillValue = NaN ;
		step:long_name = "time since forecast_reference_time" ;
		step:standard_name = "forecast_period" ;
		step:units = "hours" ;
	int64 heightAboveSea ;
		heightAboveSea:long_name = "original GRIB coordinate for key: level(heightAboveSea)" ;
		heightAboveSea:units = "1" ;
	double latitude(latitude) ;
		latitude:_FillValue = NaN ;
		latitude:units = "degrees_north" ;
		latitude:standard_name = "latitude" ;
		latitude:long_name = "latitude" ;
		latitude:stored_direction = "decreasing" ;
	double longitude(longitude) ;
		longitude:_FillValue = NaN ;
		longitude:units = "degrees_east" ;
		longitude:standard_name = "longitude" ;
		longitude:long_name = "longitude" ;
	double valid_time ;
		valid_time:_FillValue = NaN ;
		valid_time:standard_name = "time" ;
		valid_time:long_name = "time" ;
		valid_time:units = "seconds since 1970-01-01" ;
		valid_time:calendar = "proleptic_gregorian" ;
	float paramId_0(latitude, longitude) ;
		paramId_0:_FillValue = NaNf ;
		paramId_0:GRIB_paramId = 0LL ;
		paramId_0:GRIB_dataType = "ra" ;
		paramId_0:GRIB_missingValue = 9999LL ;
		paramId_0:GRIB_numberOfPoints = 24500000LL ;
		paramId_0:GRIB_typeOfLevel = "heightAboveSea" ;
		paramId_0:GRIB_NV = 0LL ;
		paramId_0:GRIB_stepUnits = 1LL ;
		paramId_0:GRIB_stepType = "instant" ;
		paramId_0:GRIB_gridType = "regular_ll" ;
		paramId_0:GRIB_gridDefinitionDescription = "Latitude/longitude " ;
		paramId_0:GRIB_Nx = 7000LL ;
		paramId_0:GRIB_iDirectionIncrementInDegrees = 0.01 ;
		paramId_0:GRIB_iScansNegatively = 0LL ;
		paramId_0:GRIB_longitudeOfFirstGridPointInDegrees = 230.005 ;
		paramId_0:GRIB_longitudeOfLastGridPointInDegrees = 299.994998 ;
		paramId_0:GRIB_Ny = 3500LL ;
		paramId_0:GRIB_jDirectionIncrementInDegrees = 0.01 ;
		paramId_0:GRIB_jPointsAreConsecutive = 0LL ;
		paramId_0:GRIB_jScansPositively = 0LL ;
		paramId_0:GRIB_latitudeOfFirstGridPointInDegrees = 54.995 ;
		paramId_0:GRIB_latitudeOfLastGridPointInDegrees = 20.005001 ;
		paramId_0:long_name = "original GRIB paramId: 0" ;
		paramId_0:units = "1" ;
		paramId_0:coordinates = "step valid_time time heightAboveSea" ;

// global attributes:
		:GRIB_edition = 2LL ;
		:GRIB_centre = "161" ;
		:GRIB_centreDescription = "161" ;
		:GRIB_subCentre = 0LL ;
		:Conventions = "CF-1.7" ;
		:institution = "161" ;
		:history = "2019-12-16T16:42:33 GRIB to CDM+CF via cfgrib-0.9.7.7.dev0/ecCodes-2.15.0 with {\"source\": \"/Users/amici/develop/ECM/cfgrib/MRMS_MergedReflectivityQCComposite_00.50_20191216-044830.grib2\", \"filter_by_keys\": {}, \"encode_cf\": [\"parameter\", \"time\", \"geography\", \"vertical\"]}" ;
}
```

**Comment by alexamici** [comment]
BTW, the initial message is an *xarray* future warning (that I will silence in the next release), no issue there, and the secondo message:
```Exception ignored in: <function Pool.__del__ at 0x119206ee0>
Traceback (most recent call last):
  File "/Users/dian/work/anaconda/envs/mypy3env/lib/python3.8/multiprocessing/pool.py", line 268, in __del__
  File "/Users/dian/work/anaconda/envs/mypy3env/lib/python3.8/multiprocessing/queues.py", line 362, in put
AttributeError: 'NoneType' object has no attribute 'dumps'
```
is an ignored exception in a `__del__` method from multiprocessing, so I think you can ignore it as well.

The resulting file, looks fine.

**Comment by dmfay** [comment]
You're right, I didn't realize the final exception was ignored 🤦‍♀ Thanks!
