### ISSUE TITLE
just installed cfgrib. "TypeError" on selfcheck and upon import

### ISSUE THREAD

**Issue by IreneCrisologo** [ecmwf/cfgrib#121]
Hi, i just installed cfgrib on Windows using `conda install -c conda-forge cfgrib`, then installed the dependencies using `conda install -c conda-forge eccodes`.

I tried the selfcheck `python -m cfgrib selfcheck` and it returned this error:

```
Traceback (most recent call last):
  File "C:\Users\iac6311\AppData\Local\Continuum\anaconda3\envs\saveurproj\lib\runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\iac6311\AppData\Local\Continuum\anaconda3\envs\saveurproj\lib\runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Users\iac6311\AppData\Local\Continuum\anaconda3\envs\saveurproj\lib\runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\iac6311\AppData\Local\Continuum\anaconda3\envs\saveurproj\lib\site-packages\cfgrib\__init__.py", line 20, in <module>
    from .dataset import Dataset, DatasetBuildError, open_file, open_fileindex
  File "C:\Users\iac6311\AppData\Local\Continuum\anaconda3\envs\saveurproj\lib\site-packages\cfgrib\dataset.py", line 265, in <module>
    @attr.attrs(eq=False)
TypeError: attrs() got an unexpected keyword argument 'eq'
```

I have Python 3.7.3 on my machine.

**Comment by alexamici** [comment]
D'oh! You are right, this is a bug in the conda package, not in *cfgrib* itself, but it is ok to track it here.

You should be abto to fix it by upgrading the *attrs* package, I'd use:`$ conda update attrs`, but I'm not a conda expert.

**Comment by alexamici** [comment]
I just updated the *conda-forge* package. The binary package should propagate shortly. Thanks again!

**Comment by IreneCrisologo** [comment]
Thank you! :)
