### ISSUE TITLE
gridType 'lambert not supported?

### ISSUE THREAD

**Issue by mstrahl** [ecmwf/cfgrib#133]
Your documentation refers to gridTypes that eccodes support, would also be supported in cfgrib. I am trying to use cfgrib.to_grib with a xarray dataset in lambert azimuthal equal area, which eccodes understands as lambert. I added the global attribute gridType:lambert, but it gives an error that gridType not detected nor set. How should it be set? 

CF conventions require a grid_mapping:lambert_azimuthal_equal_area, which is also in the global attributes. also a OGC wkt is giving as the spatial_ref attribute. 

Thanks for any help
Mikko

`(base) smartmet@pesc:~/data/hops/sfcst/hops_data/oper_finland$ python3 ~/bin/hops-raw_to_cf.py 2020-01-01 e42 hops_sfc_org/sfc_20200101/oper_finland_domain_coords.nc 'hops_sfc_org/sfc_20200101/fcast_e42/hops_ens_2020-0*.nc'
/home/smartmet/.local/lib/python3.6/site-packages/cfgrib/xarray_to_grib.py:254: FutureWarning: GRIB write support is experimental, DO NOT RELY ON IT!
  warnings.warn("GRIB write support is experimental, DO NOT RELY ON IT!", FutureWarning)
Traceback (most recent call last):
  File "/home/smartmet/bin/hops-raw_to_cf.py", line 73, in <module>
    cfgrib.to_grib(dsm,'hops-seas-'+origintime+'-mineral-laea-'+prefix+'.grb', grib_keys={'edition': 2})
  File "/home/smartmet/.local/lib/python3.6/site-packages/cfgrib/xarray_to_grib.py", line 269, in to_grib
    return canonical_dataset_to_grib(*args, **kwargs)
  File "/home/smartmet/.local/lib/python3.6/site-packages/cfgrib/xarray_to_grib.py", line 265, in canonical_dataset_to_grib
    canonical_dataarray_to_grib(data_var, file, grib_keys=real_grib_keys, **kwargs)
  File "/home/smartmet/.local/lib/python3.6/site-packages/cfgrib/xarray_to_grib.py", line 215, in canonical_dataarray_to_grib
    raise ValueError("required grib_key 'gridType' not passed nor auto-detected")
ValueError: required grib_key 'gridType' not passed nor auto-detected`

**Comment by mstrahl** [comment]
My mistake! Lambert in eccodes refers to Lambert Conformal, not LAEA, but it would still be nice to know how one passes the gribKeys into a xarray dataset.
