### ISSUE TITLE
Error in outer (orthogonal) indexing

### ISSUE THREAD

**Issue by aurghs** [ecmwf/cfgrib#157]
Orthogonal selection fails (cfgrib version:  0.9.8.4):
```python
arr = xr.open_dataarray('cfgrib_indexing_test.grib', engine='cfgrib')
```
```python
print(arr)

<xarray.DataArray 't2m' (latitude: 9, longitude: 5)>
array([[297.49146, 298.2317 , 299.21997, 298.2395 , 295.9348 ],
       [297.7102 , 297.69067, 298.4856 , 298.02466, 296.62036],
       [298.04224, 297.79224, 297.8391 , 297.87622, 298.17896],
       [298.25513, 298.11255, 298.12622, 298.12036, 298.22974],
       [298.32544, 298.28833, 298.27466, 298.26685, 298.25903],
       [298.41333, 298.38208, 298.38013, 298.3977 , 298.39185],
       [298.47778, 298.4817 , 298.53052, 298.55005, 298.55005],
       [298.5852 , 298.59497, 298.67114, 298.6848 , 298.67896],
       [298.74927, 298.74146, 298.78442, 298.7981 , 298.78833]], dtype=float32)
Coordinates:
    number      int64 ...
    time        datetime64[ns] ...
    step        timedelta64[ns] ...
    surface     int64 ...
  * latitude    (latitude) float64 42.0 41.75 41.5 41.25 ... 40.5 40.25 40.0
  * longitude   (longitude) float64 12.0 12.25 12.5 12.75 13.0
    valid_time  datetime64[ns] ...
```
cfgrib_indexing_test.grib is available here: [cfgrib_indexing_test.grib.zip](https://github.com/ecmwf/cfgrib/files/5122094/cfgrib_indexing_test.grib.zip)

Anyway, in my tests, the selection fails always when it's done on all the dimensions with nonscalar indexes.

```python
arr.isel(longitude=[0, 1], latitude=[0, 1])
```
expected output: 
```python
<xarray.DataArray 't2m' (latitude: 2, longitude: 2)>
array([[297.49146, 298.2317 ],
       [297.7102 , 297.69067]], dtype=float32)
Coordinates:
    surface     int64 0
    step        timedelta64[ns] 00:00:00
    time        datetime64[ns] 2020-07-01
    valid_time  datetime64[ns] 2020-07-01
    number      int64 0
  * longitude   (longitude) float64 12.0 12.25
  * latitude    (latitude) float64 42.0 41.75
```

obtained stack trace:
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/barghini/devel/xarray/xarray/core/common.py", line 135, in __repr__
    return formatting.array_repr(self)
  File "/Users/barghini/devel/xarray/xarray/core/formatting.py", line 478, in array_repr
    short_data_repr(arr),
  File "/Users/barghini/devel/xarray/xarray/core/formatting.py", line 463, in short_data_repr
    return short_numpy_repr(array)
  File "/Users/barghini/devel/xarray/xarray/core/formatting.py", line 437, in short_numpy_repr
    array = np.asarray(array)
  File "/usr/local/Caskroom/miniconda/base/envs/xarray-tests/lib/python3.7/site-packages/numpy/core/_asarray.py", line 83, in asarray
    return array(a, dtype, copy=False, order=order)
  File "/Users/barghini/devel/xarray/xarray/core/common.py", line 132, in __array__
    return np.asarray(self.values, dtype=dtype)
  File "/Users/barghini/devel/xarray/xarray/core/dataarray.py", line 570, in values
    return self.variable.values
  File "/Users/barghini/devel/xarray/xarray/core/variable.py", line 459, in values
    return _as_array_or_item(self._data)
  File "/Users/barghini/devel/xarray/xarray/core/variable.py", line 262, in _as_array_or_item
    data = np.asarray(data)
  File "/usr/local/Caskroom/miniconda/base/envs/xarray-tests/lib/python3.7/site-packages/numpy/core/_asarray.py", line 83, in asarray
    return array(a, dtype, copy=False, order=order)
  File "/Users/barghini/devel/xarray/xarray/core/indexing.py", line 677, in __array__
    self._ensure_cached()
  File "/Users/barghini/devel/xarray/xarray/core/indexing.py", line 674, in _ensure_cached
    self.array = NumpyIndexingAdapter(np.asarray(self.array))
  File "/usr/local/Caskroom/miniconda/base/envs/xarray-tests/lib/python3.7/site-packages/numpy/core/_asarray.py", line 83, in asarray
    return array(a, dtype, copy=False, order=order)
  File "/Users/barghini/devel/xarray/xarray/core/indexing.py", line 653, in __array__
    return np.asarray(self.array, dtype=dtype)
  File "/usr/local/Caskroom/miniconda/base/envs/xarray-tests/lib/python3.7/site-packages/numpy/core/_asarray.py", line 83, in asarray
    return array(a, dtype, copy=False, order=order)
  File "/Users/barghini/devel/xarray/xarray/core/indexing.py", line 557, in __array__
    return np.asarray(array[self.key], dtype=None)
  File "/Users/barghini/devel/xarray/xarray/backends/cfgrib_.py", line 32, in __getitem__
    key, self.shape, indexing.IndexingSupport.OUTER, self._getitem
  File "/Users/barghini/devel/xarray/xarray/core/indexing.py", line 840, in explicit_indexing_adapter
    result = NumpyIndexingAdapter(np.asarray(result))[numpy_indices]
  File "/Users/barghini/devel/xarray/xarray/core/indexing.py", line 1276, in __getitem__
    return array[key]
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
```

Note that with usually this selection works with dataarrays:
```python
arr = xr.DataArray(np.arange(9 * 5).reshape((9, 5)), dims=('latitude', 'longitude'))
arr.isel(longitude=[0,1], latitude=[0,1])

<xarray.DataArray (latitude: 2, longitude: 2)>
array([[0, 1],
       [5, 6]])
Dimensions without coordinates: latitude, longitude
```

**Comment by alexamici** [comment]
Closed in xarray
