### ISSUE TITLE
Inaccessible fields in HRRRX

### ISSUE THREAD

**Issue by Plantain** [ecmwf/cfgrib#160]
Many fields from the NOAA HRRRX seem to be unreadable with cfgrib.
They show up with grib_dump / grib_ls (also backed by eccodes?), but don't appear to be openable with cfgrib.

For example, try opening hpbl from this GRIB file.
Shows up with the shortName correctly in grib_dump:
  shortName = hpbl;

But with cfgrib:
>>> xr.open_dataset("/mnt/data/downloads/2026118002500", engine='cfgrib', backend_kwargs={'filter_by_keys': {'shortName': 'hpbl'}} )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/plantain/data-layer2/venv/lib/python3.8/site-packages/xarray/backends/api.py", line 519, in open_dataset
    store = backends.CfGribDataStore(
  File "/home/plantain/data-layer2/venv/lib/python3.8/site-packages/xarray/backends/cfgrib_.py", line 43, in __init__
    self.ds = cfgrib.open_file(filename, **backend_kwargs)
  File "/home/plantain/data-layer2/venv/lib/python3.8/site-packages/cfgrib/dataset.py", line 651, in open_file
    index = open_fileindex(path, grib_errors, indexpath, index_keys).subindex(filter_by_keys)
  File "/home/plantain/data-layer2/venv/lib/python3.8/site-packages/cfgrib/dataset.py", line 573, in build_dataset_components
    print(index.filter_by_keys)
  File "/home/plantain/data-layer2/venv/lib/python3.8/site-packages/cfgrib/messages.py", line 388, in __getitem__
    print(self.header_values)
KeyError: 'paramId'
>>> 

Sample file: https://static.skysight.io/2026118002500.grib2

**Comment by shahramn** [comment]
I tried grib_ls (using ecCodes v2.18.0) on the file 2026118002500.grib2 and cannot see any fields with the shortName of "hpbl".
Are you using some special local tables?

**Comment by Plantain** [comment]
/usr/bin/grib_ls -v
ecCodes Version 2.10.0

Not using any local tables.

**Comment by Plantain** [comment]
Actually, I am now not able to reproduce it showing shortName = hpbl now. Not sure how that's happened.

**Comment by alexamici** [comment]
@Plantain can I close this issue then?
