### ISSUE TITLE
Issue writing Grib File

### ISSUE THREAD

**Issue by enyfeo** [ecmwf/cfgrib#161]
Hi Alex,

I am trying to write the output of a regular_ll grid from netcdf to grib.

The original file contents  
```
ds
<xarray.Dataset>
Dimensions:  (lat: 1500, lon: 3600, time: 123)
Coordinates:
  * lon      (lon) float64 -179.9 -179.8 -179.8 -179.6 ... 179.8 179.9 180.0
  * lat      (lat) float64 89.95 89.85 89.75 89.65 ... -59.75 -59.85 -59.95
  * time     (time) datetime64[ns] 1981-01-02 1981-01-03 ... 1981-05-04
Data variables:
    dis      (time, lat, lon) float64 nan nan nan nan nan ... nan nan nan nan
Attributes:
    settingsfile:     /lus/snx11062/scratch/ma/maca/glofas/glofas_seas_hind3....
    date_created:     Fri Sep 11 08:44:54 2020
    Source_Software:  Lisflood Python
    institution:      European Commission DG Joint Research Centre (JRC)
    creator_name:     Peter Burek, A de Roo, Johan van der Knijff
    source:           Lisflood output maps
    keywords:         Lisflood, EFAS, GLOFAS
    Conventions:      CF-1.6
```

I am creating weekly averages of the discharge data in the file.
This yields : 

```
>>> waver
<xarray.Dataset>
Dimensions:  (lat: 1500, lon: 3600, time: 16)
Coordinates:
  * lat      (lat) float64 89.95 89.85 89.75 89.65 ... -59.75 -59.85 -59.95
  * time     (time) datetime64[ns] 1981-01-12 1981-01-19 ... 1981-04-27
  * lon      (lon) float64 -179.9 -179.8 -179.8 -179.6 ... 179.8 179.9 180.0
Data variables:
    dis      (time, lat, lon) float64 0.0 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0
```

`cfgrib.to_grib(waver,'test.grib',grib_keys={'gridType':'regular_ll'})`

When I try to read the file back in with xarray I receive an error:

```
>>> x=xr.open_dataset('test.grib',engine='cfgrib')
Ignoring index file '/perm/ma/maca/glofas/seas/test.grib.90c91.idx' older than GRIB file
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/apps/python3/3.6.10-01/lib/python3.6/site-packages/xarray/backends/api.py", line 538, in open_dataset
    ds = maybe_decode_store(store)
  File "/usr/local/apps/python3/3.6.10-01/lib/python3.6/site-packages/xarray/backends/api.py", line 453, in maybe_decode_store
    use_cftime=use_cftime,
  File "/usr/local/apps/python3/3.6.10-01/lib/python3.6/site-packages/xarray/conventions.py", line 587, in decode_cf
    ds = Dataset(vars, attrs=attrs)
  File "/usr/local/apps/python3/3.6.10-01/lib/python3.6/site-packages/xarray/core/dataset.py", line 540, in __init__
    data_vars, coords, compat="broadcast_equals"
  File "/usr/local/apps/python3/3.6.10-01/lib/python3.6/site-packages/xarray/core/merge.py", line 467, in merge_data_and_coords
    objects, compat, join, explicit_coords=explicit_coords, indexes=indexes
  File "/usr/local/apps/python3/3.6.10-01/lib/python3.6/site-packages/xarray/core/merge.py", line 558, in merge_core
    dims = calculate_dimensions(variables)
  File "/usr/local/apps/python3/3.6.10-01/lib/python3.6/site-packages/xarray/core/dataset.py", line 205, in calculate_dimensions
    % (dim, size, k, dims[dim], last_used[dim])
ValueError: conflicting sizes for dimension 'latitude': length 31 on 't' and length 32086 on 'latitude'
>>> 
```

NetCDF file outputs ok and is readable.

**Comment by meteoDaniel** [comment]
Just a question: Why you do not use NetCDF if it makes no problems?

**Comment by enyfeo** [comment]
Hi @meteoDaniel 
Because we work in grib. As then we can archive into MARS.

**Comment by meteoDaniel** [comment]
And what about to write single timestamped files? 

Nevertheless you have broke down the whole file because length 32086 and 31 does not match any dimensions you have stored. What I see is that you have coordinates but no dimensions defined compared to the example in the README. And maybe it could help to have a meshgrid as latitude and longitude. Another idea is that you write latitude and not lat. Hope this could help you to find a solution.
