### ISSUE TITLE
Can't open multiple files

### ISSUE THREAD

**Issue by vk496** [ecmwf/cfgrib#168]
Hello,

First, thank you for work. cfgrib is really useful and simplify a lot working with gribs!

I'm new with gribs and have some troubles to use `open_mfdataset` with `cfgrib` engine. I want to open grib files from directories instead of concatenating them in one file before opening.

The two files I'm trying to open are:

```python
>>> xr.open_dataset('a.grib', engine='cfgrib')
<xarray.Dataset>
Dimensions:     (latitude: 521, longitude: 741)
Coordinates:
    time        datetime64[ns] ...
    step        timedelta64[ns] ...
    surface     int64 ...
  * latitude    (latitude) float64 72.0 71.9 71.8 71.7 ... 20.3 20.2 20.1 20.0
  * longitude   (longitude) float64 -32.0 -31.9 -31.8 -31.7 ... 41.8 41.9 42.0
    valid_time  datetime64[ns] ...
Data variables:
    paramId_0   (latitude, longitude) float32 ...
Attributes:
...
```

```python
>>> xr.open_dataset('b.grib', engine='cfgrib')
<xarray.Dataset>
Dimensions:     (latitude: 521, longitude: 741)
Coordinates:
    time        datetime64[ns] ...
    step        timedelta64[ns] ...
    surface     int64 ...
  * latitude    (latitude) float64 72.0 71.9 71.8 71.7 ... 20.3 20.2 20.1 20.0
  * longitude   (longitude) float64 -32.0 -31.9 -31.8 -31.7 ... 41.8 41.9 42.0
    valid_time  datetime64[ns] ...
Data variables:
    paramId_0   (latitude, longitude) float32 ...
Attributes:
...
```

If I manually concatenate them and open them, works perfectly:

```python
>>> xr.open_dataset('BDAP/PA/test.grib', engine='cfgrib')
<xarray.Dataset>
Dimensions:     (latitude: 521, longitude: 741, step: 2)
Coordinates:
    time        datetime64[ns] ...
  * step        (step) timedelta64[ns] 03:00:00 06:00:00
    surface     int64 ...
  * latitude    (latitude) float64 72.0 71.9 71.8 71.7 ... 20.3 20.2 20.1 20.0
  * longitude   (longitude) float64 -32.0 -31.9 -31.8 -31.7 ... 41.8 41.9 42.0
    valid_time  (step) datetime64[ns] ...
Data variables:
    paramId_0   (step, latitude, longitude) float32 ...
Attributes:
...
```

But when I try to do the same with `open_mfdataset` (using the `step` for concatenation), it doesn't work the same:

```python
>>> xr.open_mfdataset(all_files[0:2], engine='cfgrib', combine="by_coords", concat_dim="step")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/valentin.kivachuk/miniconda3/envs/PredPrec-env/lib/python3.6/site-packages/xarray/backends/api.py", line 952, in open_mfdataset
    combine_attrs="drop",
  File "/home/valentin.kivachuk/miniconda3/envs/PredPrec-env/lib/python3.6/site-packages/xarray/core/combine.py", line 760, in combine_by_coords
    list(datasets_with_same_vars)
  File "/home/valentin.kivachuk/miniconda3/envs/PredPrec-env/lib/python3.6/site-packages/xarray/core/combine.py", line 107, in _infer_concat_order_from_coords
    "Could not find any dimension coordinates to use to "
ValueError: Could not find any dimension coordinates to use to order the datasets for concatenation
```

What I'm doing wrong?

Thank you in advance :)

**Comment by meteoDaniel** [comment]
I am running into the same issue. with a list of u and v wind component files. I guess it is not supported to open multiple files with different variables. 
Am I right @alexamici ?

**Comment by ShaneMill1** [comment]
I am running into this issue as well and tried to use step, time, and valid_time

**Comment by deweatherman** [comment]
Not sure if this is still an issue; I stumbled with the same error for a slightly different application. I found that using combine = 'nested'  and providing the dimension to concatenate (e.g. concat_dim='step' in your case) solves the issue.
