### ISSUE TITLE
DatasetBuildError

### ISSUE THREAD

**Issue by chris-haste** [ecmwf/cfgrib#170]
I have a grib2 file which looks like this
```
grib_ls T+06_1800.WND
T+06_1800.WND
edition      centre       date         dataType     gridType     stepRange    typeOfLevel  level        shortName    packingType  
2            egrr         20201028     fc           regular_ll   6            isobaricInhPa  200          t            grid_jpeg   
2            egrr         20201028     fc           regular_ll   6            isobaricInhPa  175          t            grid_jpeg   
2            egrr         20201028     fc           regular_ll   6            isobaricInhPa  150          t            grid_jpeg   
2            egrr         20201028     fc           regular_ll   6            isobaricInhPa  100          t            grid_jpeg   
2            egrr         20201028     fc           regular_ll   6            isobaricInhPa  850          gh           grid_jpeg   
2            egrr         20201028     fc           regular_ll   6            isobaricInhPa  700          gh           grid_jpeg   
2            egrr         20201028     fc           regular_ll   6            isobaricInhPa  600          gh           grid_jpeg   
2            egrr         20201028     fc           regular_ll   6            isobaricInhPa  500          gh           grid_jpeg   
2            egrr         20201028     fc           regular_ll   6            isobaricInhPa  400          gh           grid_jpeg   
2            egrr         20201028     fc           regular_ll   6            isobaricInhPa  350          gh           grid_jpeg   
2            egrr         20201028     fc           regular_ll   6            isobaricInhPa  300          gh           grid_jpeg   
2            egrr         20201028     fc           regular_ll   6            isobaricInhPa  275          gh           grid_jpeg   
2            egrr         20201028     fc           regular_ll   6            isobaricInhPa  250          gh           grid_jpeg   
2            egrr         20201028     fc           regular_ll   6            isobaricInhPa  225          gh           grid_jpeg   
2            egrr         20201028     fc           regular_ll   6            isobaricInhPa  200          gh           grid_jpeg   
2            egrr         20201028     fc           regular_ll   6            isobaricInhPa  175          gh           grid_jpeg   
2            egrr         20201028     fc           regular_ll   6            isobaricInhPa  150          gh           grid_jpeg   
2            egrr         20201028     fc           regular_ll   6            isobaricInhPa  100          gh           grid_jpeg   
2            egrr         20201028     fc           regular_ll   6            isobaricInhPa  850          r            grid_jpeg   
2            egrr         20201028     fc           regular_ll   6            isobaricInhPa  700          r            grid_jpeg   
2            egrr         20201028     fc           regular_ll   6            isobaricInhPa  600          r            grid_jpeg   
2            egrr         20201028     fc           regular_ll   6            isobaricInhPa  500          r            grid_jpeg   
2            egrr         20201028     fc           regular_ll   6            maxWind      0            u            grid_jpeg   
2            egrr         20201028     fc           regular_ll   6            maxWind      0            v            grid_jpeg   
2            egrr         20201028     fc           regular_ll   6            maxWind      0            icaht        grid_jpeg   
2            egrr         20201028     fc           regular_ll   6            isobaricInhPa  750          u            grid_jpeg   
2            egrr         20201028     fc           regular_ll   6            isobaricInhPa  450          u            grid_jpeg   
2            egrr         20201028     fc           regular_ll   6            isobaricInhPa  125          u            grid_jpeg   
2            egrr         20201028     fc           regular_ll   6            isobaricInhPa  750          v            grid_jpeg   
2            egrr         20201028     fc           regular_ll   6            isobaricInhPa  450          v            grid_jpeg   
2            egrr         20201028     fc           regular_ll   6            isobaricInhPa  125          v            grid_jpeg   
2            egrr         20201028     fc           regular_ll   6            isobaricInhPa  750          t            grid_jpeg   
2            egrr         20201028     fc           regular_ll   6            isobaricInhPa  450          t            grid_jpeg   
2            egrr         20201028     fc           regular_ll   6            isobaricInhPa  125          t            grid_jpeg   
2            egrr         20201028     fc           regular_ll   6            isobaricInhPa  750          gh           grid_jpeg   
2            egrr         20201028     fc           regular_ll   6            isobaricInhPa  450          gh           grid_jpeg   
2            egrr         20201028     fc           regular_ll   6            isobaricInhPa  125          gh           grid_jpeg   
2            egrr         20201028     fc           regular_ll   6            isobaricInhPa  750          r            grid_jpeg   
2            egrr         20201028     fc           regular_ll   6            isobaricInhPa  850          u            grid_jpeg   
2            egrr         20201028     fc           regular_ll   6            isobaricInhPa  700          u            grid_jpeg   
2            egrr         20201028     fc           regular_ll   6            isobaricInhPa  600          u            grid_jpeg   
2            egrr         20201028     fc           regular_ll   6            isobaricInhPa  500          u            grid_jpeg   
2            egrr         20201028     fc           regular_ll   6            isobaricInhPa  400          u            grid_jpeg   
2            egrr         20201028     fc           regular_ll   6            isobaricInhPa  350          u            grid_jpeg   
2            egrr         20201028     fc           regular_ll   6            isobaricInhPa  300          u            grid_jpeg   
2            egrr         20201028     fc           regular_ll   6            isobaricInhPa  275          u            grid_jpeg   
2            egrr         20201028     fc           regular_ll   6            isobaricInhPa  250          u            grid_jpeg   
2            egrr         20201028     fc           regular_ll   6            isobaricInhPa  225          u            grid_jpeg   
2            egrr         20201028     fc           regular_ll   6            isobaricInhPa  200          u            grid_jpeg   
2            egrr         20201028     fc           regular_ll   6            isobaricInhPa  175          u            grid_jpeg   
2            egrr         20201028     fc           regular_ll   6            isobaricInhPa  150          u            grid_jpeg   
2            egrr         20201028     fc           regular_ll   6            isobaricInhPa  100          u            grid_jpeg   
2            egrr         20201028     fc           regular_ll   6            isobaricInhPa  850          v            grid_jpeg   
2            egrr         20201028     fc           regular_ll   6            isobaricInhPa  700          v            grid_jpeg   
2            egrr         20201028     fc           regular_ll   6            isobaricInhPa  600          v            grid_jpeg   
2            egrr         20201028     fc           regular_ll   6            isobaricInhPa  500          v            grid_jpeg   
2            egrr         20201028     fc           regular_ll   6            isobaricInhPa  400          v            grid_jpeg   
2            egrr         20201028     fc           regular_ll   6            isobaricInhPa  350          v            grid_jpeg   
2            egrr         20201028     fc           regular_ll   6            isobaricInhPa  300          v            grid_jpeg   
2            egrr         20201028     fc           regular_ll   6            isobaricInhPa  275          v            grid_jpeg   
2            egrr         20201028     fc           regular_ll   6            isobaricInhPa  250          v            grid_jpeg   
2            egrr         20201028     fc           regular_ll   6            isobaricInhPa  225          v            grid_jpeg   
2            egrr         20201028     fc           regular_ll   6            isobaricInhPa  200          v            grid_jpeg   
2            egrr         20201028     fc           regular_ll   6            isobaricInhPa  175          v            grid_jpeg   
2            egrr         20201028     fc           regular_ll   6            isobaricInhPa  150          v            grid_jpeg   
2            egrr         20201028     fc           regular_ll   6            isobaricInhPa  100          v            grid_jpeg   
2            egrr         20201028     fc           regular_ll   6            isobaricInhPa  850          t            grid_jpeg   
2            egrr         20201028     fc           regular_ll   6            isobaricInhPa  700          t            grid_jpeg   
2            egrr         20201028     fc           regular_ll   6            isobaricInhPa  600          t            grid_jpeg   
2            egrr         20201028     fc           regular_ll   6            isobaricInhPa  500          t            grid_jpeg   
2            egrr         20201028     fc           regular_ll   6            isobaricInhPa  400          t            grid_jpeg   
2            egrr         20201028     fc           regular_ll   6            isobaricInhPa  350          t            grid_jpeg   
2            egrr         20201028     fc           regular_ll   6            isobaricInhPa  300          t            grid_jpeg   
2            egrr         20201028     fc           regular_ll   6            isobaricInhPa  275          t            grid_jpeg   
2            egrr         20201028     fc           regular_ll   6            isobaricInhPa  250          t            grid_jpeg   
2            egrr         20201028     fc           regular_ll   6            isobaricInhPa  225          t            grid_jpeg   
2            egrr         20201028     fc           regular_ll   6            tropopause   0            icaht        grid_jpeg   
2            egrr         20201028     fc           regular_ll   6            tropopause   0            t            grid_jpeg   
78 of 78 messages in T+06_1800.WND```

There are 5 sections with a shortname of 'r' - relative humidity. This data is only present for pressure levels 850, 750, 700, 600 and 500

When I try to open this file with this
```
ds = cfgrib.open_file("T+09_1800.WND", filter_by_keys={"typeOfLevel": "isobaricInhPa"})
```
it returns an error, but continues to open the file. The error returned is this
```
skipping variable: paramId==157 shortName='r'
Traceback (most recent call last):
  File "/home/chris/grib/venv/lib/python3.8/site-packages/cfgrib/dataset.py", line 602, in build_dataset_components
    dict_merge(variables, coord_vars)
  File "/home/chris/grib/venv/lib/python3.8/site-packages/cfgrib/dataset.py", line 536, in dict_merge
    raise DatasetBuildError(
cfgrib.dataset.DatasetBuildError: key present and new value is different: key='isobaricInhPa' value=Variable(dimensions=('isobaricInhPa',), data=array([850, 750, 700, 600, 500, 450, 400, 350, 300, 275, 250, 225, 200,
       175, 150, 125, 100])) new_value=Variable(dimensions=('isobaricInhPa',), data=array([850, 750, 700, 600, 500]))
```

I have two questions.
1. Is the above error anything I should be concerned about?
2. How can I filter to just open the 'r' value data?

**Comment by alexamici** [comment]
@chris-haste you can try with `filter_by_keys={"shortName": "r"}`

**Comment by aaronspring** [comment]
thanks. works nicely for me: https://nbviewer.jupyter.org/github/pangeo-data/climpred/blob/ad944bf9af8d4bdc24d48c49be809e2f6332cecb/docs/source/examples/NWP/NWP_GEFS_6h_forecasts.ipynb
