### ISSUE TITLE
Opening grib file AWS S3 with CF Grib?

### ISSUE THREAD

**Issue by tdhopper** [ecmwf/cfgrib#198]
I'm trying to open a grib2 file directly from a (private) S3 bucket using 

```
xr.open_dataset("s3://<bucket_name>/vertical_velocity_pressure.grib", engine="cfgrib")
```

But I get this error: 

```
Can't create file '/Users/tim.hopper/s3:/bucket-name/file-name.grib.90c91.idx'
Traceback (most recent call last):
  File "/Users/tim.hopper/.venv/lib/python3.7/site-packages/cfgrib/messages.py", line 342, in from_indexpath_or_filestream
    with compat_create_exclusive(indexpath) as new_index_file:
  File "/Users/tim.hopper/.pyenv/versions/3.7.8/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/Users/tim.hopper/.venv/lib/python3.7/site-packages/cfgrib/messages.py", line 274, in compat_create_exclusive
    fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/tim.hopper/s3:/bucket-name/file-name.grib.90c91.idx'
Can't read index file '/Users/tim.hopper/s3:/bucket-name/file-name.grib.90c91.idx'
Traceback (most recent call last):
  File "/Users/tim.hopper/.venv/lib/python3.7/site-packages/cfgrib/messages.py", line 352, in from_indexpath_or_filestream
    index_mtime = os.path.getmtime(indexpath)
  File "/Users/tim.hopper/.pyenv/versions/3.7.8/lib/python3.7/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/Users/tim.hopper/s3:/bucket-name/file-name.grib.90c91.idx'
Traceback (most recent call last):
  File "src/data_catalog/x.py", line 3, in <module>
    xr.open_dataset(r"s3://bucket-name/file-name.grib", engine="cfgrib")
  File "/Users/tim.hopper/.venv/lib/python3.7/site-packages/xarray/backends/api.py", line 572, in open_dataset
    store = opener(filename_or_obj, **extra_kwargs, **backend_kwargs)
  File "/Users/tim.hopper/.venv/lib/python3.7/site-packages/xarray/backends/cfgrib_.py", line 45, in __init__
    self.ds = cfgrib.open_file(filename, **backend_kwargs)
  File "/Users/tim.hopper/.venv/lib/python3.7/site-packages/cfgrib/dataset.py", line 650, in open_file
    index = open_fileindex(path, grib_errors, indexpath, index_keys).subindex(filter_by_keys)
  File "/Users/tim.hopper/.venv/lib/python3.7/site-packages/cfgrib/dataset.py", line 637, in open_fileindex
    return stream.index(index_keys, indexpath=indexpath)
  File "/Users/tim.hopper/.venv/lib/python3.7/site-packages/cfgrib/messages.py", line 269, in index
    return FileIndex.from_indexpath_or_filestream(self, index_keys, indexpath)
  File "/Users/tim.hopper/.venv/lib/python3.7/site-packages/cfgrib/messages.py", line 370, in from_indexpath_or_filestream
    return cls.from_filestream(filestream, index_keys)
  File "/Users/tim.hopper/.venv/lib/python3.7/site-packages/cfgrib/messages.py", line 297, in from_filestream
    for message in filestream:
  File "/Users/tim.hopper/.venv/lib/python3.7/site-packages/cfgrib/messages.py", line 240, in __iter__
    with open(self.path, 'rb') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/tim.hopper/s3:/bucket-name/file-name.grib'
```

I tried fiddling with `indexpath=""` but that doesn't seem to help either.

Is reading directly from s3 supported, and, if so, am I doing something wrong?

**Comment by martindurant** [comment]
cfgrib does *not* understand remote files - it converts back to a string path, implicitly local, to be passed to the C-lib. To use with fsspec automatically, it's `open_local` and a caching URL is the convenience route made for this.

**Comment by tdhopper** [comment]
@martindurant 🙏

**Comment by tdhopper** [comment]
@martindurant Is there a way to automatically use `open_local` with intake-xarray?

**Comment by martindurant** [comment]
Yes, intake_xarray knows about this, it should be enough to change your URL to "simplecache::s3://<bucket_name>/vertical_velocity_pressure.grib" with the netcdf driver.
